name: Java CI with Maven

on:
  push: 
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Release
      uses: softprops/action-gh-release@v2
      with: 
        files: |
          server/target/*.zip
          server/target/*.tar.gz
        fail_on_unmatched_files: true
